# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyDuino.ui'
#
# Created: Thu Aug 23 22:40:47 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PyDuino(object):
    def setupUi(self, PyDuino):
        PyDuino.setObjectName(_fromUtf8("PyDuino"))
        PyDuino.resize(331, 288)
        self.centralwidget = QtGui.QWidget(PyDuino)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.readComboBox = QtGui.QComboBox(self.tab)
        self.readComboBox.setObjectName(_fromUtf8("readComboBox"))
        self.readComboBox.addItem(_fromUtf8(""))
        self.readComboBox.addItem(_fromUtf8(""))
        self.readComboBox.addItem(_fromUtf8(""))
        self.readComboBox.addItem(_fromUtf8(""))
        self.readComboBox.addItem(_fromUtf8(""))
        self.readComboBox.addItem(_fromUtf8(""))
        self.readComboBox.addItem(_fromUtf8(""))
        self.readComboBox.addItem(_fromUtf8(""))
        self.readComboBox.addItem(_fromUtf8(""))
        self.readComboBox.addItem(_fromUtf8(""))
        self.readComboBox.addItem(_fromUtf8(""))
        self.readComboBox.addItem(_fromUtf8(""))
        self.readComboBox.addItem(_fromUtf8(""))
        self.readComboBox.addItem(_fromUtf8(""))
        self.readComboBox.addItem(_fromUtf8(""))
        self.readComboBox.addItem(_fromUtf8(""))
        self.readComboBox.addItem(_fromUtf8(""))
        self.readComboBox.addItem(_fromUtf8(""))
        self.readComboBox.addItem(_fromUtf8(""))
        self.readComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.readComboBox, 1, 0, 1, 1)
        self.readButton = QtGui.QPushButton(self.tab)
        self.readButton.setObjectName(_fromUtf8("readButton"))
        self.gridLayout_2.addWidget(self.readButton, 1, 1, 1, 1)
        self.readLcdNumber = QtGui.QLCDNumber(self.tab)
        self.readLcdNumber.setObjectName(_fromUtf8("readLcdNumber"))
        self.gridLayout_2.addWidget(self.readLcdNumber, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.dial = QtGui.QDial(self.tab_2)
        self.dial.setMaximum(255)
        self.dial.setObjectName(_fromUtf8("dial"))
        self.gridLayout_3.addWidget(self.dial, 0, 0, 1, 1)
        self.analogWriteLcdNumber = QtGui.QLCDNumber(self.tab_2)
        self.analogWriteLcdNumber.setObjectName(_fromUtf8("analogWriteLcdNumber"))
        self.gridLayout_3.addWidget(self.analogWriteLcdNumber, 0, 1, 1, 1)
        self.analogWriteComboBox = QtGui.QComboBox(self.tab_2)
        self.analogWriteComboBox.setObjectName(_fromUtf8("analogWriteComboBox"))
        self.analogWriteComboBox.addItem(_fromUtf8(""))
        self.analogWriteComboBox.addItem(_fromUtf8(""))
        self.analogWriteComboBox.addItem(_fromUtf8(""))
        self.analogWriteComboBox.addItem(_fromUtf8(""))
        self.analogWriteComboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.analogWriteComboBox, 1, 0, 1, 1)
        self.analogWriteButton = QtGui.QPushButton(self.tab_2)
        self.analogWriteButton.setObjectName(_fromUtf8("analogWriteButton"))
        self.gridLayout_3.addWidget(self.analogWriteButton, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.digitalWriteStatus = QtGui.QComboBox(self.tab_3)
        self.digitalWriteStatus.setObjectName(_fromUtf8("digitalWriteStatus"))
        self.digitalWriteStatus.addItem(_fromUtf8(""))
        self.digitalWriteStatus.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.digitalWriteStatus, 1, 1, 1, 1)
        self.digitalWriteButton = QtGui.QPushButton(self.tab_3)
        self.digitalWriteButton.setObjectName(_fromUtf8("digitalWriteButton"))
        self.gridLayout_4.addWidget(self.digitalWriteButton, 1, 2, 1, 1)
        self.digitalWriteLcdNumber = QtGui.QLCDNumber(self.tab_3)
        self.digitalWriteLcdNumber.setObjectName(_fromUtf8("digitalWriteLcdNumber"))
        self.gridLayout_4.addWidget(self.digitalWriteLcdNumber, 0, 0, 1, 3)
        self.digitalWriteComboBox = QtGui.QComboBox(self.tab_3)
        self.digitalWriteComboBox.setObjectName(_fromUtf8("digitalWriteComboBox"))
        self.digitalWriteComboBox.addItem(_fromUtf8(""))
        self.digitalWriteComboBox.addItem(_fromUtf8(""))
        self.digitalWriteComboBox.addItem(_fromUtf8(""))
        self.digitalWriteComboBox.addItem(_fromUtf8(""))
        self.digitalWriteComboBox.addItem(_fromUtf8(""))
        self.digitalWriteComboBox.addItem(_fromUtf8(""))
        self.digitalWriteComboBox.addItem(_fromUtf8(""))
        self.digitalWriteComboBox.addItem(_fromUtf8(""))
        self.digitalWriteComboBox.addItem(_fromUtf8(""))
        self.digitalWriteComboBox.addItem(_fromUtf8(""))
        self.digitalWriteComboBox.addItem(_fromUtf8(""))
        self.digitalWriteComboBox.addItem(_fromUtf8(""))
        self.digitalWriteComboBox.addItem(_fromUtf8(""))
        self.digitalWriteComboBox.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.digitalWriteComboBox, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        PyDuino.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PyDuino)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 331, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSerial_Port = QtGui.QMenu(self.menubar)
        self.menuSerial_Port.setObjectName(_fromUtf8("menuSerial_Port"))
        PyDuino.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(PyDuino)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        PyDuino.setStatusBar(self.statusbar)
        self.actionSerial_Port = QtGui.QAction(PyDuino)
        self.actionSerial_Port.setObjectName(_fromUtf8("actionSerial_Port"))
        self.menuSerial_Port.addAction(self.actionSerial_Port)
        self.menubar.addAction(self.menuSerial_Port.menuAction())

        self.retranslateUi(PyDuino)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.dial, QtCore.SIGNAL(_fromUtf8("dialMoved(int)")), self.analogWriteLcdNumber.display)
        QtCore.QMetaObject.connectSlotsByName(PyDuino)

    def retranslateUi(self, PyDuino):
        PyDuino.setWindowTitle(QtGui.QApplication.translate("PyDuino", "PyDuino", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(0, QtGui.QApplication.translate("PyDuino", "D 0", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(1, QtGui.QApplication.translate("PyDuino", "D 1", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(2, QtGui.QApplication.translate("PyDuino", "D 2", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(3, QtGui.QApplication.translate("PyDuino", "D 3", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(4, QtGui.QApplication.translate("PyDuino", "D 4", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(5, QtGui.QApplication.translate("PyDuino", "D 5", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(6, QtGui.QApplication.translate("PyDuino", "D 6", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(7, QtGui.QApplication.translate("PyDuino", "D 7", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(8, QtGui.QApplication.translate("PyDuino", "D 8", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(9, QtGui.QApplication.translate("PyDuino", "D 9", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(10, QtGui.QApplication.translate("PyDuino", "D 10", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(11, QtGui.QApplication.translate("PyDuino", "D 11", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(12, QtGui.QApplication.translate("PyDuino", "D 12", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(13, QtGui.QApplication.translate("PyDuino", "D 13", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(14, QtGui.QApplication.translate("PyDuino", "A 0", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(15, QtGui.QApplication.translate("PyDuino", "A 1", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(16, QtGui.QApplication.translate("PyDuino", "A 2", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(17, QtGui.QApplication.translate("PyDuino", "A 3", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(18, QtGui.QApplication.translate("PyDuino", "A 4", None, QtGui.QApplication.UnicodeUTF8))
        self.readComboBox.setItemText(19, QtGui.QApplication.translate("PyDuino", "A 5", None, QtGui.QApplication.UnicodeUTF8))
        self.readButton.setText(QtGui.QApplication.translate("PyDuino", "Read", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("PyDuino", "Read", None, QtGui.QApplication.UnicodeUTF8))
        self.analogWriteComboBox.setItemText(0, QtGui.QApplication.translate("PyDuino", "Pin 3", None, QtGui.QApplication.UnicodeUTF8))
        self.analogWriteComboBox.setItemText(1, QtGui.QApplication.translate("PyDuino", "Pin 5", None, QtGui.QApplication.UnicodeUTF8))
        self.analogWriteComboBox.setItemText(2, QtGui.QApplication.translate("PyDuino", "Pin 6", None, QtGui.QApplication.UnicodeUTF8))
        self.analogWriteComboBox.setItemText(3, QtGui.QApplication.translate("PyDuino", "Pin 10", None, QtGui.QApplication.UnicodeUTF8))
        self.analogWriteComboBox.setItemText(4, QtGui.QApplication.translate("PyDuino", "Pin 11", None, QtGui.QApplication.UnicodeUTF8))
        self.analogWriteButton.setText(QtGui.QApplication.translate("PyDuino", "Write", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("PyDuino", "Analog Write", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalWriteStatus.setItemText(0, QtGui.QApplication.translate("PyDuino", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalWriteStatus.setItemText(1, QtGui.QApplication.translate("PyDuino", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalWriteButton.setText(QtGui.QApplication.translate("PyDuino", "Write", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalWriteComboBox.setItemText(0, QtGui.QApplication.translate("PyDuino", "D 0", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalWriteComboBox.setItemText(1, QtGui.QApplication.translate("PyDuino", "D 1", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalWriteComboBox.setItemText(2, QtGui.QApplication.translate("PyDuino", "D 2", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalWriteComboBox.setItemText(3, QtGui.QApplication.translate("PyDuino", "D 3", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalWriteComboBox.setItemText(4, QtGui.QApplication.translate("PyDuino", "D 4", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalWriteComboBox.setItemText(5, QtGui.QApplication.translate("PyDuino", "D 5", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalWriteComboBox.setItemText(6, QtGui.QApplication.translate("PyDuino", "D 6", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalWriteComboBox.setItemText(7, QtGui.QApplication.translate("PyDuino", "D 7", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalWriteComboBox.setItemText(8, QtGui.QApplication.translate("PyDuino", "D 8", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalWriteComboBox.setItemText(9, QtGui.QApplication.translate("PyDuino", "D 9", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalWriteComboBox.setItemText(10, QtGui.QApplication.translate("PyDuino", "D 10", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalWriteComboBox.setItemText(11, QtGui.QApplication.translate("PyDuino", "D 11", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalWriteComboBox.setItemText(12, QtGui.QApplication.translate("PyDuino", "D 12", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalWriteComboBox.setItemText(13, QtGui.QApplication.translate("PyDuino", "D 13", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("PyDuino", "Digital Write", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("PyDuino", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSerial_Port.setTitle(QtGui.QApplication.translate("PyDuino", "Config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSerial_Port.setText(QtGui.QApplication.translate("PyDuino", "Serial Port", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    PyDuino = QtGui.QMainWindow()
    ui = Ui_PyDuino()
    ui.setupUi(PyDuino)
    PyDuino.show()
    sys.exit(app.exec_())

